[package]
name = "sniff"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sniff"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = {version="0.30.1", features=["init-if-needed"]}
spl-token-metadata-interface = "0.3.3"
anchor-spl = "0.30.1"
solana-program = "=1.18.17"
uuid = { version = "0.8.*", features = ["serde", "v5"] }
session-keys = { path = "../gpl_session", features = ["no-entrypoint", "cpi"] }