[toolchain]
anchor_version = "0.30.1" 
solana_version = "1.18.17" 

[features]
seeds = true
skip-lint = false

[programs.localnet]
sniff = "7RG7EnGnLoPqRmjcNQijaAZEuUNn2qFJUyEJBSTkTUfv"
session_keys = "4mYFD9UAPw9E8qpL4HgDHde1hRCrjEs42X3eFUJufcEC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./deployment-keypair/local/id.json"

[workspace]
types = "types"
members = [
  "programs/sniff",
  "programs/gpl_session",
]

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --parallel"

[test]
upgradeable = true
startup_wait = 10000

[[test.genesis]]
# address = "4mYFD9UAPw9E8qpL4HgDHde1hRCrjEs42X3eFUJufcEC"
address = "KeyspM2ssCJbqUhQ4k7sveSiY4WjnYsrXkC8oDbwde5"
program="test-programs/session_keys.so"
