[toolchain]
anchor_version = "0.30.1" 
solana_version = "1.18.17" 

[features]
seeds = true
skip-lint = false

[programs.localnet]
sniff = "5QZqUCtYrCgLkXRvjPSL5PyPg4cuHrMp58Ts2dBR7vCG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./deployment-keypair/local/id.json"

[workspace]
types = "types"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true
startup_wait = 10000

[[test.genesis]]
address = "KeyspM2ssCJbqUhQ4k7sveSiY4WjnYsrXkC8oDbwde5"
program="test-programs/session_keys.so"
